server:
    port: 9001

conf_dir: @conf_repo@

spring:
  profiles:
    active: native
  application:
    name: configserver
    bus:
      enabled: true
  cloud:
    config:
      server:
        native:
          search-locations: file:${conf_dir}
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8788
        instance.service-host-type: ip
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: @eureka.client.serviceUrl.defaultZone@
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
